// Mocks generated by Mockito 5.4.6 from annotations
// in pdf_reader_app/test/unit/features/reader/pdf_reader_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pdf_reader_app/core/data/models/pdf_document.dart' as _i5;
import 'package:pdf_reader_app/core/data/repositories/pdf_repository.dart'
    as _i3;
import 'package:pdf_reader_app/core/utils/result.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedPreferencesPdfRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesPdfRepository extends _i1.Mock
    implements _i3.SharedPreferencesPdfRepository {
  MockSharedPreferencesPdfRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.PdfDocument>>> getAllPdfs() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPdfs, []),
            returnValue: _i4.Future<_i2.Result<List<_i5.PdfDocument>>>.value(
              _FakeResult_0<List<_i5.PdfDocument>>(
                this,
                Invocation.method(#getAllPdfs, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<_i5.PdfDocument>>>);

  @override
  _i4.Future<_i2.Result<_i3.PaginatedPdfs>> getPagedPdfs({
    int? offset = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPagedPdfs, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.Result<_i3.PaginatedPdfs>>.value(
              _FakeResult_0<_i3.PaginatedPdfs>(
                this,
                Invocation.method(#getPagedPdfs, [], {
                  #offset: offset,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i3.PaginatedPdfs>>);

  @override
  _i4.Future<_i2.Result<_i5.PdfDocument?>> getPdfById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPdfById, [id]),
            returnValue: _i4.Future<_i2.Result<_i5.PdfDocument?>>.value(
              _FakeResult_0<_i5.PdfDocument?>(
                this,
                Invocation.method(#getPdfById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.PdfDocument?>>);

  @override
  _i4.Future<_i2.Result<List<_i5.PdfDocument>>> getRecentPdfs({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentPdfs, [], {#limit: limit}),
            returnValue: _i4.Future<_i2.Result<List<_i5.PdfDocument>>>.value(
              _FakeResult_0<List<_i5.PdfDocument>>(
                this,
                Invocation.method(#getRecentPdfs, [], {#limit: limit}),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<_i5.PdfDocument>>>);

  @override
  _i4.Future<_i2.Result<List<_i5.PdfDocument>>> getFavoritePdfs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoritePdfs, []),
            returnValue: _i4.Future<_i2.Result<List<_i5.PdfDocument>>>.value(
              _FakeResult_0<List<_i5.PdfDocument>>(
                this,
                Invocation.method(#getFavoritePdfs, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<_i5.PdfDocument>>>);

  @override
  _i4.Future<_i2.Result<_i5.PdfDocument>> addPdf(_i5.PdfDocument? document) =>
      (super.noSuchMethod(
            Invocation.method(#addPdf, [document]),
            returnValue: _i4.Future<_i2.Result<_i5.PdfDocument>>.value(
              _FakeResult_0<_i5.PdfDocument>(
                this,
                Invocation.method(#addPdf, [document]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.PdfDocument>>);

  @override
  _i4.Future<_i2.Result<_i5.PdfDocument>> updatePdf(
    _i5.PdfDocument? document,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePdf, [document]),
            returnValue: _i4.Future<_i2.Result<_i5.PdfDocument>>.value(
              _FakeResult_0<_i5.PdfDocument>(
                this,
                Invocation.method(#updatePdf, [document]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.PdfDocument>>);

  @override
  _i4.Future<_i2.Result<void>> deletePdf(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePdf, [id]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#deletePdf, [id])),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<_i5.PdfDocument>> toggleFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [id]),
            returnValue: _i4.Future<_i2.Result<_i5.PdfDocument>>.value(
              _FakeResult_0<_i5.PdfDocument>(
                this,
                Invocation.method(#toggleFavorite, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.PdfDocument>>);

  @override
  _i4.Future<_i2.Result<void>> updateProgress(
    String? documentId,
    int? page,
    int? scrollOffset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [
              documentId,
              page,
              scrollOffset,
            ]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#updateProgress, [
                  documentId,
                  page,
                  scrollOffset,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<String?>> generateThumbnail(String? pdfId) =>
      (super.noSuchMethod(
            Invocation.method(#generateThumbnail, [pdfId]),
            returnValue: _i4.Future<_i2.Result<String?>>.value(
              _FakeResult_0<String?>(
                this,
                Invocation.method(#generateThumbnail, [pdfId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<String?>>);

  @override
  _i4.Future<_i2.Result<_i5.PdfDocument>> updateThumbnail(
    String? pdfId,
    String? thumbnailPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateThumbnail, [pdfId, thumbnailPath]),
            returnValue: _i4.Future<_i2.Result<_i5.PdfDocument>>.value(
              _FakeResult_0<_i5.PdfDocument>(
                this,
                Invocation.method(#updateThumbnail, [pdfId, thumbnailPath]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.PdfDocument>>);
}
