// Mocks generated by Mockito 5.4.6 from annotations
// in pdf_reader_app/test/widget/features/reader/pdf_chat_panel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pdf_reader_app/core/data/datasources/local/chat_message_entity.dart'
    as _i11;
import 'package:pdf_reader_app/core/data/datasources/local/chat_session_entity.dart'
    as _i9;
import 'package:pdf_reader_app/core/data/models/pdf_document.dart' as _i10;
import 'package:pdf_reader_app/core/data/repositories/chat_repository.dart'
    as _i8;
import 'package:pdf_reader_app/core/services/pdf_ai_service.dart' as _i3;
import 'package:pdf_reader_app/core/utils/result.dart' as _i2;
import 'package:pdf_reader_app/features/reader/presentation/providers/pdf_chat_state.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PdfAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdfAIService extends _i1.Mock implements _i3.PdfAIService {
  MockPdfAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> extractTextFromPdf(
    String? filePath, {
    int? maxPages,
    void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extractTextFromPdf,
              [filePath],
              {#maxPages: maxPages, #onProgress: onProgress},
            ),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(
                  #extractTextFromPdf,
                  [filePath],
                  {#maxPages: maxPages, #onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> generateSummary(String? pdfText) =>
      (super.noSuchMethod(
            Invocation.method(#generateSummary, [pdfText]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#generateSummary, [pdfText]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> extractData(String? pdfText, String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#extractData, [pdfText, prompt]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#extractData, [pdfText, prompt]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> chatWithDocument(
    String? pdfText,
    String? question,
    List<_i6.ChatMessage>? history,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#chatWithDocument, [pdfText, question, history]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#chatWithDocument, [
                  pdfText,
                  question,
                  history,
                ]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  void logAuthCheck(_i7.FirebaseAuth? auth) => super.noSuchMethod(
    Invocation.method(#logAuthCheck, [auth]),
    returnValueForMissingStub: null,
  );

  @override
  void logAuthFailure() => super.noSuchMethod(
    Invocation.method(#logAuthFailure, []),
    returnValueForMissingStub: null,
  );

  @override
  void logOperationStart(String? operation, Map<String, dynamic>? metadata) =>
      super.noSuchMethod(
        Invocation.method(#logOperationStart, [operation, metadata]),
        returnValueForMissingStub: null,
      );

  @override
  void logOperationSuccess(String? operation, Map<String, dynamic>? metadata) =>
      super.noSuchMethod(
        Invocation.method(#logOperationSuccess, [operation, metadata]),
        returnValueForMissingStub: null,
      );

  @override
  void logOperationFailure(
    String? operation,
    Object? error, [
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#logOperationFailure, [operation, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void logCloudFunctionCall(String? functionName, Map<String, dynamic>? data) =>
      super.noSuchMethod(
        Invocation.method(#logCloudFunctionCall, [functionName, data]),
        returnValueForMissingStub: null,
      );

  @override
  void logCloudFunctionResponse(Map<String, dynamic>? data) =>
      super.noSuchMethod(
        Invocation.method(#logCloudFunctionResponse, [data]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i8.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i9.ChatSessionEntity>> getOrCreateSession(
    String? pdfId,
    _i10.PdfDocument? pdf,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateSession, [pdfId, pdf]),
            returnValue: _i4.Future<_i2.Result<_i9.ChatSessionEntity>>.value(
              _FakeResult_0<_i9.ChatSessionEntity>(
                this,
                Invocation.method(#getOrCreateSession, [pdfId, pdf]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i9.ChatSessionEntity>>);

  @override
  _i4.Future<_i2.Result<_i9.ChatSessionEntity?>> getSessionByPdfId(
    String? pdfId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionByPdfId, [pdfId]),
            returnValue: _i4.Future<_i2.Result<_i9.ChatSessionEntity?>>.value(
              _FakeResult_0<_i9.ChatSessionEntity?>(
                this,
                Invocation.method(#getSessionByPdfId, [pdfId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i9.ChatSessionEntity?>>);

  @override
  _i4.Future<_i2.Result<List<_i8.RepositoryChatMessage>>> getMessages(
    String? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [sessionId]),
            returnValue:
                _i4.Future<_i2.Result<List<_i8.RepositoryChatMessage>>>.value(
                  _FakeResult_0<List<_i8.RepositoryChatMessage>>(
                    this,
                    Invocation.method(#getMessages, [sessionId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i8.RepositoryChatMessage>>>);

  @override
  _i4.Future<_i2.Result<_i11.ChatMessageEntity>> addMessage(
    String? sessionId,
    _i8.RepositoryChatMessage? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMessage, [sessionId, message]),
            returnValue: _i4.Future<_i2.Result<_i11.ChatMessageEntity>>.value(
              _FakeResult_0<_i11.ChatMessageEntity>(
                this,
                Invocation.method(#addMessage, [sessionId, message]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i11.ChatMessageEntity>>);

  @override
  _i4.Future<_i2.Result<void>> updateSessionMetadata({
    required String? sessionId,
    required int? messageCount,
    int? lastMessageAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionMetadata, [], {
              #sessionId: sessionId,
              #messageCount: messageCount,
              #lastMessageAt: lastMessageAt,
            }),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#updateSessionMetadata, [], {
                  #sessionId: sessionId,
                  #messageCount: messageCount,
                  #lastMessageAt: lastMessageAt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<_i9.ChatSessionEntity>>> getRecentSessions({
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentSessions, [], {#limit: limit}),
            returnValue:
                _i4.Future<_i2.Result<List<_i9.ChatSessionEntity>>>.value(
                  _FakeResult_0<List<_i9.ChatSessionEntity>>(
                    this,
                    Invocation.method(#getRecentSessions, [], {#limit: limit}),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i9.ChatSessionEntity>>>);

  @override
  _i4.Future<_i2.Result<void>> deleteSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [sessionId]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#deleteSession, [sessionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> archiveSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveSession, [sessionId]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#archiveSession, [sessionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);
}
