#!/bin/bash
# Dartdoc Generation Script
# Generates API documentation using dartdoc with best practices for AI agent scanning

set -e

PROJECT_DIR="/Users/macbook/testclaude"
DOC_DIR="$PROJECT_DIR/doc/api"
OUTPUT_DIR="$PROJECT_DIR/dartdoc"

echo "📚 Generating Dartdoc Documentation"
echo "===================================="
echo ""

# Parse command line arguments
FORMAT="html"
VERBOSE=false
VALIDATE=false
OPEN_BROWSER=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --json)
      FORMAT="json"
      shift
      ;;
    --verbose)
      VERBOSE=true
      shift
      ;;
    --validate)
      VALIDATE=true
      shift
      ;;
    --open)
      OPEN_BROWSER=true
      shift
      ;;
    --help)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --json      Generate JSON output instead of HTML (better for AI parsing)"
      echo "  --verbose   Show detailed output during generation"
      echo "  --validate  Validate documentation completeness"
      echo "  --open      Open documentation in browser after generation"
      echo "  --help      Show this help message"
      exit 0
      ;;
    *)
      echo "❌ Unknown option: $1"
      echo "Use --help for usage information"
      exit 1
      ;;
  esac
done

# Step 1: Clean previous documentation
echo "1️⃣  Cleaning previous documentation..."
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Step 2: Create dartdoc_options.yaml for best practices
echo ""
echo "2️⃣  Creating dartdoc configuration..."
cd "$PROJECT_DIR" || exit 1

cat > dartdoc_options.yaml << 'EOF'
# Dartdoc configuration for best practices
# Auto-generated by generate-dartdoc.sh

# Exclude generated files
exclude:
  - 'lib/**/*.g.dart'
  - 'lib/**/*.freezed.dart'

# Exclude internal cache implementation
  - 'lib/core/cache/cache_manager.dart'

# Organize documentation into categories
categories:
  core:
    name: Core
    classes: [AppLogger, Result, ThumbnailService]
  features:
    name: Features
    classes: [LibraryNotifier, ReaderNotifier, SettingsNotifier]
  data:
    name: Data Layer
    classes: [PdfDocument, AppSettings, PdfRepository]

# Show warnings for broken links
validateLinks: true

# Use emoji in category headers
categoryOrder: [core, features, data]

# Ignore ambiguous doc references
ignore:
  - ambiguous-doc-reference
EOF

echo "✅ Configuration created: dartdoc_options.yaml"

# Step 3: Run dartdoc with best practices
echo ""
echo "3️⃣  Running dartdoc..."

# Build dartdoc command as array
DARTDOC_ARGS=()

# Add output directory
DARTDOC_ARGS+=(-o "$OUTPUT_DIR")

# Add format option (JSON not directly supported, will use HTML)
if [ "$FORMAT" = "json" ]; then
  echo "   ⚠️  Note: dart doc doesn't support JSON output directly"
  echo "   Using HTML format instead (still parseable by AI)"
fi
echo "   Format: HTML (human-readable and AI-parseable)"

# Show command if verbose
if [ "$VERBOSE" = true ]; then
  echo ""
  echo "   Running: dart doc ${DARTDOC_ARGS[*]}"
  echo ""
fi

# Execute dartdoc
if dart doc "${DARTDOC_ARGS[@]}" 2>&1; then
  echo "✅ Documentation generated successfully"
else
  echo "❌ ERROR: dartdoc generation failed"
  # Clean up the options file on error
  rm -f dartdoc_options.yaml
  exit 1
fi

# Clean up options file
rm -f dartdoc_options.yaml

# Step 4: Validate documentation if requested
if [ "$VALIDATE" = true ]; then
  echo ""
  echo "4️⃣  Validating documentation..."

  # Check for undocumented public APIs
  UNDOCUMENTED=$(find "$OUTPUT_DIR" -name "*.html" -o -name "*.json" 2>/dev/null | wc -l | tr -d ' ')

  # Check for files with no documentation comments
  echo "   Checking for undocumented public APIs..."

  # Use dart analyze to find undocumented members
  cd "$PROJECT_DIR" || exit 1

  # Check for public APIs without documentation
  # Note: This is a simple check; consider using lints with 'package:lints' for comprehensive checking
  echo "   ℹ️  For comprehensive validation, consider adding 'public_member_api_docs' lint to analysis_options.yaml"
fi

# Step 5: Generate summary index for AI scanning
echo ""
echo "5️⃣  Generating AI-friendly index..."

cat > "$OUTPUT_DIR/index.md" << 'EOF'
# API Documentation Index

This documentation is auto-generated by dartdoc and serves as a reference for:
- **AI Agents**: Scan this documentation to understand the codebase API
- **Developers**: Quick reference for public APIs and their usage

## Quick Links

### Core Module
- **Data Models**: `PdfDocument`, `AppSettings`, `ReadingProgress`
- **Repositories**: `PdfRepository`, `SettingsRepository`
- **Services**: `PdfIntentHandler`, `ThumbnailService`, `AnalyticsService`
- **Utils**: `AppLogger`, `Result` type

### Features
- **Library**: PDF library management, search, filtering
- **Reader**: PDF viewer with Syncfusion, AI chat integration
- **Settings**: App preferences, theme management
- **Auth**: Google Sign-In authentication
- **Drive**: Google Drive integration
- **Scanner**: Document scanning

## Key Patterns

### Result Type
All repository operations return `Result<T>` for type-safe error handling:
```dart
final result = await repository.getAllPdfs();
result.when(
  success: (pdfs) => print('Found ${pdfs.length} PDFs'),
  failure: (error) => print('Error: $error'),
);
```

### Riverpod Providers
State management uses code-generated providers:
```dart
@riverpod
class MyNotifier extends _$MyNotifier {
  @override
  MyState build() => MyState.initial();
}
```

### Clean Architecture
- **Data Layer**: Repositories, data sources, DTOs
- **Domain Layer**: Use cases, entities (business logic)
- **Presentation Layer**: UI, state management, navigation

## Generated Files

- **Format**: HTML/JSON
- **Tool**: dartdoc
- **Last Updated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

For the latest documentation, run:
```bash
.claude/scripts/generate-dartdoc.sh
```
EOF

echo "✅ AI index generated: $OUTPUT_DIR/index.md"

# Step 6: Generate JSON manifest for AI agents
if [ "$FORMAT" = "json" ]; then
  echo ""
  echo "6️⃣  Generating JSON manifest for AI agents..."

  # Create a simple manifest with file listings
  cat > "$OUTPUT_DIR/manifest.json" << EOF
{
  "generated_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "project": "pdf_reader_app",
  "version": "1.0.0",
  "format": "json",
  "output_dir": "$OUTPUT_DIR",
  "api_documentation": [
    "lib/core/data/models/",
    "lib/core/data/repositories/",
    "lib/core/services/",
    "lib/features/"
  ]
}
EOF

  echo "✅ JSON manifest generated: $OUTPUT_DIR/manifest.json"
fi

# Step 7: Open in browser if requested
if [ "$OPEN_BROWSER" = true ] && [ "$FORMAT" = "html" ]; then
  echo ""
  echo "7️⃣  Opening documentation in browser..."

  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    open "$OUTPUT_DIR/index.html"
  elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux
    xdg-open "$OUTPUT_DIR/index.html"
  else
    echo "   ℹ️  Please open manually: $OUTPUT_DIR/index.html"
  fi
fi

# Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Dartdoc Generation Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 Documentation location: $OUTPUT_DIR"

if [ "$FORMAT" = "html" ]; then
  echo "🌐 Open: $OUTPUT_DIR/index.html"
else
  echo "📋 JSON format for AI parsing"
  echo "📄 Manifest: $OUTPUT_DIR/manifest.json"
fi

echo "📑 AI Index: $OUTPUT_DIR/index.md"
echo ""
echo "To regenerate documentation, run:"
echo "  .claude/scripts/generate-dartdoc.sh"
echo ""
echo "For help with options:"
echo "  .claude/scripts/generate-dartdoc.sh --help"
echo ""
