// Mocks generated by Mockito 5.4.6 from annotations
// in pdf_reader_app/test/unit/features/settings/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pdf_reader_app/core/data/models/app_settings.dart' as _i5;
import 'package:pdf_reader_app/core/data/repositories/settings_repository.dart'
    as _i3;
import 'package:pdf_reader_app/core/utils/result.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i3.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AppSettings> get settingsStream =>
      (super.noSuchMethod(
            Invocation.getter(#settingsStream),
            returnValue: _i4.Stream<_i5.AppSettings>.empty(),
          )
          as _i4.Stream<_i5.AppSettings>);

  @override
  _i4.Future<_i2.Result<_i5.AppSettings>> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i4.Future<_i2.Result<_i5.AppSettings>>.value(
              _FakeResult_0<_i5.AppSettings>(
                this,
                Invocation.method(#getSettings, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.AppSettings>>);

  @override
  _i4.Future<_i2.Result<_i5.AppSettings>> updateSettings(
    _i5.AppSettings? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [settings]),
            returnValue: _i4.Future<_i2.Result<_i5.AppSettings>>.value(
              _FakeResult_0<_i5.AppSettings>(
                this,
                Invocation.method(#updateSettings, [settings]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.AppSettings>>);

  @override
  _i4.Future<_i2.Result<_i5.AppSettings>> resetToDefaults() =>
      (super.noSuchMethod(
            Invocation.method(#resetToDefaults, []),
            returnValue: _i4.Future<_i2.Result<_i5.AppSettings>>.value(
              _FakeResult_0<_i5.AppSettings>(
                this,
                Invocation.method(#resetToDefaults, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.AppSettings>>);
}
